
CREATE DATABASE IF NOT EXISTS vetPatitas;

CREATE TABLE IF NOT EXISTS vetPatitas.addresses (
    id INT NOT NULL AUTO_INCREMENT,
    street VARCHAR(50) NOT NULL,
    ext_number CHAR(6) NOT NULL,
    int_number CHAR(6),
    colony VARCHAR(50) NOT NULL,
    municipality VARCHAR(50) NOT NULL,
    state VARCHAR(50) NOT NULL,
    zip_code INT NOT NULL,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS vetPatitas.owners (
    id INT NOT NULL AUTO_INCREMENT,
    id_address INT NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    age INT,
    email VARCHAR(50) NOT NULL,
    phone VARCHAR(15),
    active BOOLEAN NOT NULL DEFAULT '1',
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT owners_ibfk_1 FOREIGN KEY (id_address) REFERENCES addresses (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS vetPatitas.pets (
    id INT NOT NULL AUTO_INCREMENT,
    id_owner INT,
    name VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    species VARCHAR(50) NOT NULL,
    breed VARCHAR(50),
    color VARCHAR(20) NOT NULL,
    weight DOUBLE NOT NULL,
    active BOOLEAN NOT NULL DEFAULT '1',
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT pets_ibfk_1 FOREIGN KEY (id_owner) REFERENCES owners (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
