/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bootcamp;

import bootcamp.hackerrank.Solution;
import bootcamp.hackerrank.august30.ramsonnote.RansomNote;

public class App {
    public static void main(String[] args) {
        new App().testHackerRank();
    }
    
    public void testHackerRank() {
    	Solution solution;
  		
  		solution = new RansomNote();
  		solution.solve();
  		
  		Solution.closeScanner();
    }
}
